src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $first_name = null;

    #[ORM\Column(length: 30)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 12)]
    private ?string $phonenumber = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPhonenumber(): ?string
    {
        return $this->phonenumber;
    }

    public function setPhonenumber(string $phonenumber): static
    {
        $this->phonenumber = $phonenumber;

        return $this;
    }
}

src/Controller/HomepageController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\SanPham;
use App\Entity\Category;
use App\Entity\User;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use App\Form\UserType;
use Knp\Component\Pager\PaginatorInterface;

class HomepageController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/feature', name: 'feature_product')]
    public function viewdetail(EntityManagerInterface $em): Response
    {
        $query = $em->createQuery('SELECT sp FROM App\Entity\SanPham sp');
        $lSp = $query->getResult();
                                
        return $this->render('homepage/sanpham.html.twig', [
            "data"=>$lSp
        ]);
    }
    #[Route('/category', name: 'app_category')]
    public function viewCate(EntityManagerInterface $em): Response
    {
        $query = $em->createQuery('SELECT category FROM App\Entity\Category category');
        $category = $query->getResult();
                                
        return $this->render('homepage/category.html.twig', [
            'category' => $category,
        ]);
    }
    #[Route('/feature/{id}', name: 'app_detailsp')]
    public function detail(EntityManagerInterface $em, int $id): Response
    {
        $sp = $em->find(SanPham::class, $id);

        return $this->render('homepage/detail.html.twig', [
            'data' => $sp,
        ]);
    }
    
    #[Route('/', name: 'homepage')]
    public function cate(EntityManagerInterface $em, UrlGeneratorInterface $urlGenerator, PaginatorInterface $paginator, Request $request): Response
    {
        $query = $em->createQuery('SELECT category FROM App\Entity\Category category');
        $category = $query->getResult();

        $query = $em->createQuery('SELECT sp FROM App\Entity\SanPham sp');
        $lSp = $query->getResult();

        $pagination = $paginator->paginate(
            $lSp, 
            $request->query->getInt('page', 1),
            8
        );

        return $this->render('homepage/index.html.twig', [
            'category' => $category,
            'data' => $pagination,
        ]);
    }

    #[Route('/category/{id}', name: 'app_productofcate')]
    public function viewCategoryProducts(EntityManagerInterface $em, int $id, Request $request): Response
    {
        $cate = $em->find(Category::class, $id);
        $lSp = $cate->getSanPhams();
        return $this->render('homepage/sanpham.html.twig', [
            "data"=>$lSp
        ]);
    }

    #[Route('/profile', name: 'profile')]
    public function profile()
    {
        $user = $this->getUser();

        return $this->render('homepage/profile.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/profile/edit', name: 'edit_profile')]
    public function editProfile(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();

        if ($request->isMethod('POST')) {
            $user->setFirstName($request->request->get('first_name'));
            $user->setLastName($request->request->get('last_name'));
            $user->setAddress($request->request->get('address'));
            $user->setPhonenumber($request->request->get('phone_number'));
            $entityManager->flush();
        
            return $this->redirectToRoute('profile');
        }

        return $this->render('homepage/settings.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/search', name: 'search_products')]
    public function search(Request $request): Response
    {
        $keyword = $request->query->get('keyword');

        $products = $this->entityManager->getRepository(SanPham::class)->findByKeyword($keyword);

        return $this->render('homepage/sanpham.html.twig', ['data' => $products]);
    }
}

templates/homepage/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categories{% endblock %}

{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{asset('css/style.css')}}" />
{% endblock %}

{% block body %}
<!-- Advertising Banner Start -->
<div class="container-fluid pb-3 pt-5">
    <div class="row px-xl-5">
        <div class="col-md-6">
            <a href="" data-ad-type="horizontal">
                <img class="img-fluid" src="images/adv1.webp" alt="Advertising Banner">
            </a>
        </div>
        <div class="col-md-6">
            <a href="" data-ad-type="horizontal">
                <img class="img-fluid" src="images/adv2.webp" alt="Advertising Banner">
            </a>
        </div>
    </div>
</div>
<!-- Advertising Banner End -->

<!-- Featured brand start -->
<section class="section section-brands mt-2 ml-5">
    <div class="container-fluid">
        <div class="section-heading">    
            <div class="box-header">
                <h2 class="hTitle">
                    <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M13 1L16.3213 3.29839H20.4189L21.6787 7L25 9.29839L23.7402 13L25 16.7016L21.6787 19L20.4189 22.7016H16.3213L13 25L9.67869 22.7016H5.58112L4.32131 19L1 16.7016L2.25981 13L1 9.29839L4.32131 7L5.58112 3.29839H9.67869L13 1Z" fill="#FF3C53" stroke="#FF3C53" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
                        <path d="M11.9614 17.7126C11.5706 18.1121 11.0429 18.3352 10.4938 18.3332C9.94465 18.3311 9.41858 18.1042 9.0305 17.7019L6.75439 15.345C6.18277 14.7531 6.19316 13.7953 6.78557 13.225C7.3468 12.6654 8.24062 12.6869 8.78106 13.2465L10.4959 15.0222L17.1788 8.10236C17.74 7.52122 18.6442 7.52122 19.2054 8.10236L19.247 8.1454C19.8082 8.72654 19.8082 9.67358 19.2366 10.2547L11.9614 17.7126Z" fill="white"></path>
                    </svg>
                    <a href="/">Featured brand</a>
                </h2>
            </div>
        </div>
        <div class="section-content">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <a class="item-img boxlazy-img" href="/search?type=product&amp;q=filter=((title%3Aproduct%20**%20acer)%7C%7C(tag%3Aproduct%3Dacer)%7C%7C(sku%3Aproduct**acer))%26%26(price%3Aproduct%3E100)" aria-label="Acer">
                            <img data-src="https://file.hstatic.net/200000636033/file/rectangle_259_eea1812015b14bc995ba6e17a9ffcd6a.png" src="https://file.hstatic.net/200000636033/file/rectangle_259_eea1812015b14bc995ba6e17a9ffcd6a.png" alt="Acer" class=" ls-is-cached lazyloaded img-fluid">
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a class="item-img boxlazy-img" href="/pages/pc-amd" aria-label="Banner">
                            <img data-src="https://file.hstatic.net/200000636033/file/rectangle_260_aedfdd6ec9904428a4566f426e42b175.png" src="https://file.hstatic.net/200000636033/file/rectangle_260_aedfdd6ec9904428a4566f426e42b175.png" alt="Banner" class=" ls-is-cached lazyloaded img-fluid">
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a class="item-img boxlazy-img" href="/pages/asus-official-store" aria-label="Banner">
							<img data-src="https://file.hstatic.net/200000636033/file/rectangle_261_91f4f7211c994176905b6bb2074e7b85.png" src="https://file.hstatic.net/200000636033/file/rectangle_261_91f4f7211c994176905b6bb2074e7b85.png" alt="Banner" class=" ls-is-cached lazyloaded">
						</a>
                    </div>
                    <div class="col-md-3">
                        <a class="item-img boxlazy-img" href="/pages/corsair-icue" aria-label="Banner">
							<img data-src="https://file.hstatic.net/200000636033/file/rectangle_263_1c5818cf69ec48a79bd139d945b014be.png" src="https://file.hstatic.net/200000636033/file/rectangle_263_1c5818cf69ec48a79bd139d945b014be.png" alt="Banner" class=" ls-is-cached lazyloaded">
						</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Featured brand end -->

<!-- Categories Start -->
<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4">
        <span class="bg-secondary pr-3">Categories</span>
    </h2>
    <div class="row px-xl-5 pb-3">
        {% for category in category %}
        <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
            <a class="text-decoration-none" href="{{ path('app_productofcate', {'id': category.id})}}">
                <div class="cat-item d-flex align-items-center mb-4">
                    <div class="overflow-hidden" style="width: 100px; height: 100px;">
                        <img class="img-fluid" src="{{ asset('uploads/sanpham/' ~ category.getPhoto()) }}" alt="">
                    </div>
                    <div class="flex-fill pl-3">
                        <h6>{{ category.getName() }}</h6>
                        {# <small class="text-body">30 Products</small> #}
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<!-- Categories End -->
{% endblock %}

templates/homepage/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product detail page{% endblock %}

{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{asset('css/style.css')}}" />
{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row px-xl-5">
        <div class="col-md-6">
            <img src="{{ asset('uploads/sanpham/' ~ data.getPhoto()) }}" alt="" class="img-fluid">
        </div>
        <div class="col-md-6">
            <h2>{{ data.getName() }}</h2>
            <hr>
            <h5 class="mb-3">Price: {{ data.getPrice() }}$</h5>
            <h5>Detailed description of {{ data.getName()}}:</h5>
            <p class="mb-3">{{ data.getDescription() }}</p>
            <hr>
            <div class="text-primary rating mt-2 mb-4">
                <span class="star-icon"><i class="fa fa-star"></i></span>
                <span class="star-icon"><i class="fa fa-star"></i></span>
                <span class="star-icon"><i class="fa fa-star"></i></span>
                <span class="star-icon"><i class="fa fa-star"></i></span>
                <span class="star-icon"><i class="fa fa-star"></i></span>
            </div>
            <form method="post" action="{{ path('app_cart_add', {'product_id': data.getId()}) }}">
                <button class="btn btn-danger rounded-2 pl-3 pr-3" type="submit" id="add-to-cart">
                    Add to Cart
                </button>
            </form>  
        </div>
    </div>
</div>
{% endblock %}

templates/homepage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block body %}
<!-- Carousel Start -->
<div class="container-fluid mb-3 mt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8">
            <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#header-carousel" data-slide-to="1"></li>
                    <li data-target="#header-carousel" data-slide-to="2"></li>
                    <li data-target="#header-carousel" data-slide-to="3"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item position-relative active" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="images/carousel-1.webp"
                            style="object-fit: cover;">
                    </div>
                    <div class="carousel-item position-relative" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="images/carousel-2.webp"
                            style="object-fit: cover;">
                    </div>
                    <div class="carousel-item position-relative" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="images/carousel-4.webp"
                            style="object-fit: cover;">
                    </div>
                    <div class="carousel-item position-relative" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="images/carousel-5.webp"
                            style="object-fit: cover;">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="product-offer mb-30" style="height: 200px;">
                <img class="img-fluid" src="images/offer-4.png" alt="">
            </div>
            <div class="product-offer mb-30" style="height: 200px;">
                <img class="img-fluid" src="images/offer-5.png" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Carousel End -->

<!-- Featured Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
            </div>
        </div>
    </div>
</div>
<!-- Featured End -->


<!-- Categories Start -->
<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4">
        <span class="bg-secondary pr-3">Categories</span>
    </h2>
    <div class="row px-xl-5 pb-3">
        {% for category in category %}
        <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
            <a class="text-decoration-none" href="{{ path('app_productofcate', {'id': category.id})}}">
                <div class="cat-item d-flex align-items-center mb-4">
                    <div class="overflow-hidden" style="width: 100px; height: 100px;">
                        <img class="img-fluid" src="{{ asset('uploads/sanpham/' ~ category.getPhoto()) }}" alt="">
                    </div>
                    <div class="flex-fill pl-3">
                        <h6>{{ category.getName() }}</h6>
                        {# <small class="text-body">30 Products</small> #}
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Categories End -->


<!-- Products Start -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4">
        <span class="bg-secondary pr-3">Featured Products</span>
    </h2>
    <div class="row px-xl-5">
        {% for sp in data %}
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1" title="{{ sp.getName()}}">
                <div class="product-item bg-light mb-4">
                    <div class="product-img position-relative overflow-hidden">
                        <img class="img-fluid w-100" src="{{ asset('uploads/sanpham/' ~ sp.getPhoto()) }}" alt="">
                    </div>
                    <div class="text-center py-4">
                        <a class="h6 text-decoration-none text-truncate" href="">{{ sp.getName() }}</a>
                        <div class="d-flex align-items-center justify-content-center mt-2">
                            <h5>{{ sp.getPrice() }} $</h5>
                        </div>
                        <div class="d-flex align-items-center justify-content-center mb-2">
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small>(99)</small>
                        </div>
                        <div class="btn" title="Add to cart">
                            <form method="post" action="{{ path('app_cart_add', {'product_id': sp.getId()}) }}">
                                <button class="btn btn-outline-danger btn-light rounded-2 pl-3 pr-3" type="submit" id="add-to-cart">
                                    <i class="bi bi-bag-plus-fill"></i>
                                </button>
                            </form>                                            
                        </div>
                        <div class="btn" title="View detail">
                            <a class="btn btn-outline-danger btn-light rounded-2 pl-3 pr-3" href="{{ path('app_detailsp', {'id': sp.id}) }}"><i class="bi bi-eye-fill"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            {% if loop.index is divisible by(4) or loop.last %}
                </div><div class="row px-xl-5">
            {% endif %}
        {% endfor %}
        <div class="pagination justify-content-center p-3">
            {% set pageCount = data.pageCount %}
            {% set currentPage = data.current %}
            
            {% if currentPage != 1 %}
                <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'page': 1})) }}" class="btn btn-outline-danger btn-light rounded-2 pl-3 pr-3 mx-1">First</a>
            {% endif %}
        
            {% for page in 1..pageCount %}
                {% if currentPage != page %}
                    <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'page': page})) }}" class="btn btn-outline-danger btn-light rounded-3 pl-3 pr-3 mx-1">{{ page }}</a>
                {% else %}
                    <span class="btn btn-outline-danger btn-light rounded-3 pl-3 pr-3 mx-1 active">{{ page }}</span>
                {% endif %}
            {% endfor %}
                <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'page': pageCount})) }}" class="btn btn-outline-danger btn-light rounded-2 pl-3 pr-3 mx-1">Last</a>
        </div>                                                                                       
    </div>
</div>
<!-- Products End -->
{% endblock %}

templates/homepage/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block body %}
<section class="vh-100" style="background-color: #f5eeee;">
  <div class="container py-5 h-90">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-7 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom text-center text-white"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
              <img src="https://lh5.googleusercontent.com/proxy/aYnkFKtr1sEXx7R_9RC9EvNwhWxJS-OPfcZxjjvo0iB-mwzPlSndUEcNCBr63nvU73R3vvKGCYoxY9_rTGadXWAyCO_U6MzzxvES4I9_k2S5fa-jaWu6y-i3qpbsCHzUGfVYCeSd0T9TDNSTX5PnC-d9vUAiNhgdTykt_inm=w1200-h630-p-k-no-nu"
                alt="Avatar" class="img-fluid my-5" style="width: 120px;" />
              <h5>Hello: {{ user.username }}!</h5>
              {# <h6>{{ user.roles|join(', ') }} </h6> #}
              <i class="far fa-edit mb-5"></i>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h5>Your information</h5>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>First name</h6>
                    <p class="text-muted">{{ user.firstname }}</p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Last name</h6>
                    <p class="text-muted">{{ user.lastname }}</p>
                  </div>
                </div>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Your address</h6>
                    <p class="text-muted">{{ user.address }}</p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Your phone number</h6>
                    <p class="text-muted">{{ user.phonenumber }}</p>
                  </div>
                </div>
                <div class="d-flex justify-content-start ml-4">
                  <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-instagram fa-lg me-3"></i></a>
                </div>
                <div class="container-fluid mt-3">
                  <span>
                    <a href="{{ path('edit_profile') }}" class="btn btn-outline-danger btn-light rounded-2">Edit Profile</a>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/homepage/settings.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profile{% endblock %}

{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{asset('css/style.css')}}" /
{% endblock %}


{% block body %}
<div class="container mt-5">
    <h2>Edit Profile</h2>
    <hr>

    <form method="post" action="{{ path('edit_profile') }}">
        <div class="mb-3">
            <label for="first_name" class="form-label">First Name:</label>
            <input type="text" id="first_name" name="first_name" value="{{ user.firstName }}" class="form-control rounded-2" required>
        </div>
        <div class="mb-3">
            <label for="last_name" class="form-label">Last Name:</label>
            <input type="text" id="last_name" name="last_name" value="{{ user.lastName }}" class="form-control rounded-2" required>
        </div>
        <div class="mb-3">
            <label for="address" class="form-label">Address:</label>
            <input type="text" id="address" name="address" value="{{ user.address }}" class="form-control rounded-2" required>
        </div>
        <div class="mb-3">
            <label for="phone_number" class="form-label">Phone Number:</label>
            <input type="text" id="phone_number" name="phone_number" value="{{ user.phoneNumber }}" class="form-control rounded-2" required>
        </div>
        <button class="btn btn-danger rounded-2 mb-4" type="submit">Save</button>
    </form>
</div>
{% endblock %}